CSU_ASP/Controllers/ShopCartController.cs
using CSU_ASP.Data.interfaces;
using CSU_ASP.Data.Models;
using CSU_ASP.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CSU_ASP.Controllers
{
    [Authorize]
    public class ShopCartController : Controller
    {

        private readonly IAllCars _carRep;
        private readonly ShopCart _shopCart;


        public ShopCartController(IAllCars carRep, ShopCart shopCart)
        {
            _carRep = carRep;
            _shopCart = shopCart;
        }

        [AllowAnonymous]
        public ViewResult Index()
        {

            if (User.Identity.IsAuthenticated)
            {
                var items = _shopCart.GetShopItems();
                _shopCart.shopItems = items;

                var obj = new ShopCartViewModel
                {
                    shopCart = _shopCart
                };
                return View(obj);
            }

            return View("Non_auth");
        }

        public RedirectToActionResult addToCart(int ID)
        {
            var item = _carRep.Cars.FirstOrDefault(i => i.id == ID);
            if (item != null)
                _shopCart.AddToCart(item);
            return RedirectToAction("Index");
        }
    }
}

CSU_ASP/Views/Shared/AllCars.cshtml
@model Car

<div class="col-lg-4">
    <img class="img-thumbnail" src="@Model.img" alt="@Model.name" />
    <h2>@Model.name</h2>
    <p>@Model.shortDesc</p>
    <p>Цена: @Model.price.ToString("c")</p>
    <p><a class="btn btn-warning" asp-controller="ShopCart" asp-action="addToCart" asp-route-ID="@Model.id">Добавить в корзину</a></p>
</div>

CSU_ASP/Views/Shared/Non_auth.cshtml
<div class="container">
    <h1>Вы не авторизованы!</h1>
    <a asp-action="Login" asp-controller="Account">Авторизация</a>
</div>

CSU_ASP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/bootstrap.min.css " rel="stylesheet" type="text/css" />
    <link href="~/css/style.css " rel="stylesheet" type="text/css" />
</head>
<header>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">CSU_ASP</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Cars/List">Машины</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Cars/List/electro">Электромобили</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Cars/List/fuel">Машины с ДВС</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/ShopCart/Index">Корзина</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container mt-5"></div>
<body>
    <div>
        @RenderBody()
    </div>
    <script src="~/js/bootstrap.min.js"></script>
</body>
</html>